# $language = "python"
# $interface = "1.0"

# Module _constants.py

# ################### CONSTANTS ####################
INPUT_FOLDER = "_input/"
TEMP_FOLDER = "ztemp/"
OUTPUT_FOLDER = "_output/"

ACCURACY_THRESHOLD_LEVEL1 = 0.5
ACCURACY_THRESHOLD_LEVEL2 = 1
ACCURACY_THRESHOLD_LEVEL3 = 1.5
ACCURACY_THRESHOLD_LEVEL4 = 2

ACCURACY_COLOR_LEVEL1 = "#3c783c"
ACCURACY_COLOR_LEVEL2 = "#56ab56"
ACCURACY_COLOR_LEVEL3 = "#ffbe00"
ACCURACY_COLOR_LEVEL4 = "#ff0e0e"
ACCURACY_COLOR_LEVEL5 = "#c00000"

LATENCY_THRESHOLD_LEVEL1 = 200
LATENCY_THRESHOLD_LEVEL2 = 300
LATENCY_THRESHOLD_LEVEL3 = 500
LATENCY_THRESHOLD_LEVEL4 = 750

LATENCY_COLOR_LEVEL1 = "#3c783c"
LATENCY_COLOR_LEVEL2 = "#56ab56"
LATENCY_COLOR_LEVEL3 = "#ffbe00"
LATENCY_COLOR_LEVEL4 = "#ff0e0e"
LATENCY_COLOR_LEVEL5 = "#c00000"

PIXEL_SIZE = 5
PLOT_X = (-170, 90)
PLOT_Y = (-60, 120)

NUM_COLUMNS = 3
FONT_SIZE = 4
MARKER = "x"
